### ISSUE TITLE
Define word module

### ISSUE THREAD

**Issue by chris2727** [EvilzoneLabs/BeastBot#27]
"a define command to utilize googles, define:[word] altgough similar to the ud module, this will give real dictionary, helpful with certain words" - DeepCopy

Should be a simple module to make. Good suggestion DeepCopy.

**Comment by ibabushkin** [comment]
This seems to be of use: http://public.oed.com/subscriber-services/sru-service/. 
But their API is a bit clumsy and returns XML we'd need to clean. So maybe this
http://developer.wordnik.com/#!/libraries#python is an option, they even provide
a python library for it. If we install it on the server running the bot, this will be a piece
of cake, otherwise might become a bit of ugly work.
Anyway, I can work on it.
-TheWormKill

**Comment by techb** [comment]
define.py has been added. It uses http://dictionary.reference.com and beautifulsoup.

Google uses something like ajax or something, so its kinda hard to grab it's data. They also stopped the dictionary api back in 2011, so the site I use works.

**Comment by ibabushkin** [comment]
Well looks as if I was too slow
UPDATE: merged into `testing`.
